### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by sidahmedabdelillah** [Axodus/axodusDotfiles#1]
Hello i am a tottal noob on linux,  and i just adore this setup of yours. I was wondering if it would work on ubuntu 20.04 and if there is a more detailed guide on seeting it up. Thank you

**Comment by muhamed1ism** [comment]
He is also using ubuntu 20.04.1.

**Comment by Axodus** [comment]
Yes, I am using Ubuntu 20.04.1 so it will work on your setup.

As for the guide, for the programs I put in the config, I have linked official installation GitHubs, as they're mostly GitHub repos.

When you finish installing you just clone the configs from my repo into you ~/.config/ folder and thats it. For the status bar (thingy on the top) you also need the extension with the settings I have inserted (see screenshot in README).

Something I did forget to include is dash-to-dock, and will be adding into the README when I get to my computer.
